### ISSUE TITLE
osx: can't build an extention library with Ruby 3.4.1

### ISSUE THREAD

**Issue by kou** [conda-forge/ruby-feedstock#140]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

We can't build an extension library with Ruby 3.4.1:

```console
$ gem install bigdecimal
Building native extensions. This could take a while...
ERROR:  Error installing bigdecimal:
	ERROR: Failed to build gem native extension.

    current directory: /Users/kou/miniconda3/share/rubygems/gems/bigdecimal-3.1.9/ext/bigdecimal
/Users/kou/miniconda3/bin/ruby extconf.rb
checking for __builtin_clz()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include=${opt-dir}/include
	--without-opt-include
	--with-opt-lib=${opt-dir}/lib
	--without-opt-lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/kou/miniconda3/bin/$(RUBY_BASE_NAME)
/Users/kou/miniconda3/lib/ruby/3.4.0/mkmf.rb:528:in 'MakeMakefile#try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

	from /Users/kou/miniconda3/lib/ruby/3.4.0/mkmf.rb:655:in 'MakeMakefile#try_compile'
	from extconf.rb:6:in 'block in Object#have_builtin_func'
	from /Users/kou/miniconda3/lib/ruby/3.4.0/mkmf.rb:1070:in 'block in MakeMakefile#checking_for'
	from /Users/kou/miniconda3/lib/ruby/3.4.0/mkmf.rb:370:in 'block (2 levels) in MakeMakefile::Logging.postpone'
	from /Users/kou/miniconda3/lib/ruby/3.4.0/mkmf.rb:340:in 'MakeMakefile::Logging.open'
	from /Users/kou/miniconda3/lib/ruby/3.4.0/mkmf.rb:370:in 'block in MakeMakefile::Logging.postpone'
	from /Users/kou/miniconda3/lib/ruby/3.4.0/mkmf.rb:340:in 'MakeMakefile::Logging.open'
	from /Users/kou/miniconda3/lib/ruby/3.4.0/mkmf.rb:366:in 'MakeMakefile::Logging.postpone'
	from /Users/kou/miniconda3/lib/ruby/3.4.0/mkmf.rb:1069:in 'MakeMakefile#checking_for'
	from extconf.rb:5:in 'Object#have_builtin_func'
	from extconf.rb:18:in '<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/kou/miniconda3/share/rubygems/extensions/arm64-darwin-20/3.4.0/bigdecimal-3.1.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/kou/miniconda3/share/rubygems/gems/bigdecimal-3.1.9 for inspection.
Results logged to /Users/kou/miniconda3/share/rubygems/extensions/arm64-darwin-20/3.4.0/bigdecimal-3.1.9/gem_make.out
```

`/Users/kou/miniconda3/share/rubygems/extensions/arm64-darwin-20/3.4.0/bigdecimal-3.1.9/mkmf.log`:

```text
DYLD_LIBRARY_PATH=.:/Users/kou/miniconda3/lib ASAN_OPTIONS=detect_leaks=0 "arm64-apple-darwin20.0.0-clang -o conftest -I/Users/kou/miniconda3/include/ruby-3.4.0/arm64-darwin20 -I/Users/kou/miniconda3/include/ruby-3.4.0/ruby/backward -I/Users/kou/miniconda3/include/ruby-3.4.0 -I. -D_FORTIFY_SOURCE=2 -isystem /Users/kou/miniconda3/include -mmacosx-version-min=11.0 -mmacosx-version-min=11.0 -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem /Users/kou/miniconda3/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/ruby_1735298644573/work=/usr/local/src/conda/ruby-3.4.1 -fdebug-prefix-map=/Users/kou/miniconda3=/usr/local/src/conda-prefix -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fdeclspec  -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wextra-tokens -Wdeprecated-declarations -Wdivision-by-zero -Wdiv-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wmisleading-indentation -Wundef -fno-common conftest.c -L. -L/Users/kou/miniconda3/lib -L. -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/kou/miniconda3/lib -L/Users/kou/miniconda3/lib -fstack-protector-strong  -arch arm64   -lruby.3.4  -lpthread  "
In file included from conftest.c:1:
In file included from /Users/kou/miniconda3/include/ruby-3.4.0/ruby.h:38:
In file included from /Users/kou/miniconda3/include/ruby-3.4.0/ruby/ruby.h:42:
In file included from /Users/kou/miniconda3/include/ruby-3.4.0/ruby/internal/memory.h:64:
/Users/kou/miniconda3/include/ruby-3.4.0/ruby/internal/stdckdint.h:48:11: error: 'stdckdint.h' file not found with <angled> include; use "quotes" instead
   48 | # include <stdckdint.h>
      |           ^~~~~~~~~~~~~
      |           "stdckdint.h"
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

```

Ruby 3.4.0 or later detects `stdckdint.h` when Ruby is built. In general, `stdckdint.h` isn't detected on macOS but conda-forge build detects it:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1121927&view=logs&j=d6b58996-039f-5e48-56bf-c3a016e5cd7f&t=dd6a23d9-2356-5264-64bf-579875a5d8d6&l=4272

```text
checking for stdckdint.h... yes
```

If `stdckdint.h` is detected in build time, `stdckdint.h` is required when building an extension library. But it's not installed automatically by `conda install -c conda-forge ruby`. So `gem install bigdecimal` is failed.

Related: https://github.com/apache/arrow-adbc/pull/2396

### Installed packages

```shell
# packages in environment at /Users/kou/miniconda3:
#
# Name                    Version                   Build  Channel
anaconda-anon-usage       0.5.0           py312hd6b623d_100  
archspec                  0.2.3              pyhd3eb1b0_0  
autoconf                  2.71            pl5321hcd07c0c_1    conda-forge
automake                  1.17            pl5321hce30654_0    conda-forge
boltons                   23.0.0          py312hca03da5_0  
brotli-python             1.0.9           py312h313beb8_8  
bzip2                     1.0.8                h80987f9_6  
c-ares                    1.19.1               h80987f9_0  
c-compiler                1.8.0                hf48404e_1    conda-forge
ca-certificates           2024.12.14           hf0a4a13_0    conda-forge
cctools                   1010.6               hf67d63f_2    conda-forge
cctools_osx-64            1010.6               hf0540ea_2    conda-forge
cctools_osx-arm64         1010.6               h623e0ac_2    conda-forge
certifi                   2024.12.14         pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h3eb5a62_0  
charset-normalizer        3.3.2              pyhd3eb1b0_0  
clang                     17.0.6          default_h360f5da_7    conda-forge
clang-17                  17.0.6          default_h146c034_7    conda-forge
clang-18                  18.1.8          default_h5c12605_5    conda-forge
clang_impl_osx-arm64      17.0.6              he47c785_23    conda-forge
clang_osx-arm64           17.0.6              h07b0088_23    conda-forge
clangxx                   17.0.6          default_h360f5da_7    conda-forge
clangxx_impl_osx-arm64    17.0.6              h50f59cd_23    conda-forge
clangxx_osx-arm64         17.0.6              h07b0088_23    conda-forge
compiler-rt               17.0.6               h856b3c1_2    conda-forge
compiler-rt_osx-64        17.0.6               hf2b8a54_2    conda-forge
compiler-rt_osx-arm64     17.0.6               h832e737_2    conda-forge
compilers                 1.8.0                hce30654_1    conda-forge
conda                     24.11.2         py312h81bd7bf_0    conda-forge
conda-anaconda-telemetry  0.1.1           py312hca03da5_0  
conda-content-trust       0.2.0           py312hca03da5_1  
conda-libmamba-solver     24.9.0             pyhd3eb1b0_0  
conda-package-handling    2.4.0           py312hca03da5_0  
conda-package-streaming   0.11.0          py312hca03da5_0  
cryptography              43.0.3          py312h8026fc7_1  
cxx-compiler              1.8.0                h18dbf2f_1    conda-forge
distro                    1.9.0           py312hca03da5_0  
expat                     2.6.4                h313beb8_0  
fmt                       9.1.0                h48ca7d4_1  
fortran-compiler          1.8.0                hc3477c4_1    conda-forge
frozendict                2.4.2           py312hca03da5_0  
gettext                   0.21.0               hbdbcc25_2  
gfortran                  13.2.0               h1ca8e4b_1    conda-forge
gfortran_impl_osx-arm64   13.2.0               h252ada1_3    conda-forge
gfortran_osx-arm64        13.2.0               h57527a5_1    conda-forge
gmp                       6.3.0                h7bae524_2    conda-forge
gnuconfig                 2020.11.07           hd8ed1ab_0    conda-forge
icu                       75.1                 hfee45f7_0    conda-forge
idna                      3.7             py312hca03da5_0  
isl                       0.26            imath32_h347afa1_101    conda-forge
jsonpatch                 1.33            py312hca03da5_1  
jsonpointer               2.1                pyhd3eb1b0_0  
krb5                      1.20.1               hf3e1bf2_1  
ld64                      951.9                h39a299f_2    conda-forge
ld64_osx-64               951.9                hdcfefba_2    conda-forge
ld64_osx-arm64            951.9                h3f9b568_2    conda-forge
libarchive                3.7.7                h3b16cec_3    conda-forge
libasprintf               0.22.5               h8414b35_3    conda-forge
libclang-cpp17            17.0.6          default_h146c034_7    conda-forge
libclang-cpp18.1          18.1.8          default_h5c12605_5    conda-forge
libcurl                   8.1.2                h912dcd9_0    conda-forge
libcxx                    19.1.6               ha82da77_1    conda-forge
libcxx-devel              17.0.6               h86353a2_6    conda-forge
libedit                   3.1.20230828         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libexpat                  2.6.4                h286801f_0    conda-forge
libffi                    3.4.4                hca03da5_1  
libgettextpo              0.22.5               h8414b35_3    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran-devel_osx-arm64 13.2.0               h5d7a38c_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libglib                   2.82.2               h07bd6cf_0    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libintl                   0.22.5               h8414b35_3    conda-forge
libllvm17                 17.0.6               h5090b49_2    conda-forge
libllvm18                 18.1.8               h5090b49_2    conda-forge
liblzma                   5.6.3                h39f12f2_1    conda-forge
libmamba                  1.5.11               haeffa04_1  
libmambapy                1.5.11          py312h15e39b3_1  
libnghttp2                1.52.0               hae82a92_0    conda-forge
libsolv                   0.7.30               h6c9b7f8_0    conda-forge
libsqlite                 3.47.2               h3f77e49_0    conda-forge
libssh2                   1.11.1               h9cc3647_0    conda-forge
libxml2                   2.13.5               h178c5d8_1    conda-forge
libzlib                   1.3.1                h8359307_2    conda-forge
llvm-openmp               14.0.6               hc6e5704_0  
llvm-tools                17.0.6               h5090b49_2    conda-forge
llvm-tools-18             18.1.8               h5090b49_2    conda-forge
lz4-c                     1.10.0               h286801f_1    conda-forge
lzo                       2.10              h93a5062_1001    conda-forge
m4                        1.4.18            h642e427_1001    conda-forge
macosx_deployment_target_osx-arm64 14.5                 hd3da6c6_2    conda-forge
make                      4.4.1                hc9fafa5_2    conda-forge
menuinst                  2.2.0           py312hca03da5_0  
mpc                       1.3.1                h8f1351a_1    conda-forge
mpfr                      4.2.1                hb693164_3    conda-forge
ncurses                   6.5                  h7bae524_1    conda-forge
openssl                   3.4.0                h39f12f2_0    conda-forge
packaging                 24.1            py312hca03da5_0  
pcre2                     10.44                h297a79d_2    conda-forge
perl                      5.32.1          7_h4614cfb_perl5    conda-forge
pip                       24.2            py312hca03da5_0  
pkg-config                0.29.2            hde07d2e_1009    conda-forge
platformdirs              3.10.0          py312hca03da5_0  
pluggy                    1.5.0           py312hca03da5_0  
pybind11-abi              5                    hd3eb1b0_0  
pycosat                   0.6.6           py312h80987f9_1  
pycparser                 2.21               pyhd3eb1b0_0  
pysocks                   1.7.1           py312hca03da5_0  
python                    3.12.8          hc22306f_1_cpython    conda-forge
python.app                3               py312h80987f9_1  
python_abi                3.12                    5_cp312    conda-forge
readline                  8.2                  h1a28f6b_0  
reproc                    14.2.4               h313beb8_2  
reproc-cpp                14.2.4               h313beb8_2  
requests                  2.32.3          py312hca03da5_1  
ruamel.yaml               0.18.6          py312h80987f9_0  
ruamel.yaml.clib          0.2.8           py312h80987f9_0  
ruby                      3.4.1                he7d92ad_0    conda-forge
rust                      1.83.0               h4ff7c5d_0    conda-forge
rust-std-aarch64-apple-darwin 1.83.0               hf6ec828_0    conda-forge
rust-std-x86_64-apple-darwin 1.83.0               h38e4360_0    conda-forge
rust_osx-arm64            1.83.0               h114d0d1_1    conda-forge
setuptools                75.1.0          py312hca03da5_0  
sigtool                   0.1.3                h44b9a77_0    conda-forge
sqlite                    3.47.2               hd7222ec_0    conda-forge
stdlibs                   2024.12.3          pyhd8ed1ab_1    conda-forge
tapi                      1300.6.5             h03f4b80_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tqdm                      4.66.5          py312h989b03a_0  
truststore                0.8.0           py312hca03da5_0  
tzdata                    2024b                h04d1e81_0  
urllib3                   2.2.3           py312hca03da5_0  
wheel                     0.44.0          py312hca03da5_0  
xz                        5.4.6                h80987f9_1  
yaml                      0.2.5                h1a28f6b_0  
yaml-cpp                  0.8.0                h313beb8_1  
zlib                      1.3.1                h8359307_2    conda-forge
zstandard                 0.23.0          py312h1a4646a_1  
zstd                      1.5.6                hb46c0d2_0    conda-forge
```

### Environment info

```shell
active environment : base
    active env location : /Users/kou/miniconda3
            shell level : 1
       user config file : /Users/kou/.condarc
 populated config files : /Users/kou/miniconda3/.condarc
          conda version : 24.11.2
    conda-build version : not installed
         python version : 3.12.8.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.11.2=0
                          __osx=15.0.1=0
                          __unix=0=0
       base environment : /Users/kou/miniconda3  (writable)
      conda av data dir : /Users/kou/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/kou/miniconda3/pkgs
                          /Users/kou/.conda/pkgs
       envs directories : /Users/kou/miniconda3/envs
                          /Users/kou/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.11.2 requests/2.32.3 CPython/3.12.8 Darwin/24.0.0 OSX/15.0.1 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.11 aau/0.5.0 c/. s/. e/.
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by kou** [comment]
Ah, sorry...
Installing `compilers` is the problem. If `compilers` is installed, we can't use clang-18 that includes `stdckdint.h`.
