### ISSUE TITLE
conda-forge's ruby attempts to install gens in the global system directory

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/ruby-feedstock#7]
I guess that it should use some directory under the PREFIX path.

**Comment by scopatz** [comment]
Prs welcome!

**Comment by SylvainCorlay** [comment]
> Prs welcome!

Did you make a bot for this? 😄

**Comment by scopatz** [comment]
hahah now that is a great idea :wink:

**Comment by SylvainCorlay** [comment]
That said, it is probably a matter of figuring out another option at the configure step. I will try to see if I can find it... althougglh I am not a Ruby person.

**Comment by scopatz** [comment]
Yeah, I am not a ruby person either.  I was just trying to fiddle around with it and so I mad the package.

**Comment by carlodri** [comment]
not a ruby person either...but [this SO answer](https://stackoverflow.com/a/16099464/4511441) says something like:

```bash
export GEM_HOME="$PREFIX/<ruby version>/gems"
export GEM_PATH="$GEM_HOME"
```

**Comment by jakirkham** [comment]
So activate/deactivate scripts would be one option. Is there an RC file solution?

**Comment by SylvainCorlay** [comment]
I wonder if this could be set at build time, so that we don't need environment variable.

**Comment by jimmynguyc** [comment]
> So activate/deactivate scripts would be one option. Is there an RC file solution?

You can specify the `gemhome` in `/etc/gemrc`, `/usr/local/etc/gemrc` or `~/.gemrc`

```
gemhome: /usr/local/.gems
```

**Comment by SylvainCorlay** [comment]
Awesome. Would ruby pick up thay rc file in `INSTALL_PREFIX/etc`?

**Comment by jimmynguyc** [comment]
I don't think so. It tries to get it in those locations (https://github.com/rubygems/rubygems/blob/master/lib/rubygems/config_file.rb#L32-L37) or from the `GEMRC` environment variable.

**Comment by scopatz** [comment]
Well, this recipe could patch `SYSTEM_CONFIG_PATH` in that file to instead look in $PATH

**Comment by scopatz** [comment]
Sorry, look in `$PREFIX`

**Comment by jakirkham** [comment]
That should be pretty easy to do.

We do something applicable here in `fontconfig` as well. Basically we apply [a patch]( https://github.com/conda-forge/fontconfig-feedstock/blob/be61df0fa594242fd94227fb4ffa59e7fa6b1553/recipe/fcf.patch#L12 ), which makes it easy to [replace the value with `sed`]( https://github.com/conda-forge/fontconfig-feedstock/blob/be61df0fa594242fd94227fb4ffa59e7fa6b1553/recipe/build.sh#L12 ) during the build. `conda-build` should pick up on the hard-coded path in the text file during packaging and stub it out for replacement at install time.

**Comment by jimmynguyc** [comment]
According to [this](https://idiosyncratic-ruby.com/42-ruby-config.html) and [this](https://www.rubydoc.info/stdlib/etc/2.0.0/Etc.sysconfdir) SYSTEM_CONFIG_PATH *should* default to `$(prefix)/etc`?

**Comment by wolfv** [comment]
trying this now.

**Comment by wolfv** [comment]
I added the following to the bottom of the build.sh script:

```
mkdir -p $PREFIX/etc
mkdir -p $PREFIX/share/rubygems/

echo "gemhome: ${PREFIX}/share/rubygems" > $PREFIX/etc/gemrc
```

and it seems to work.

There are two issues though:

- the `$PREFIX/share/rubygems/bin` paths isn't added to $PATH, we could do that through an activate script
- I get some issue when trying to execute the gem's bin: 

```
(ruby) ~/Programs/recipes/ruby-feedstock:271_windows$ ~/miniconda3/envs/ruby/share/rubygems/bin/jekyll 
Traceback (most recent call last):
	2: from /home/wolfv/miniconda3/envs/ruby/share/rubygems/bin/jekyll:23:in `<main>'
	1: from /home/wolfv/miniconda3/envs/ruby/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
/home/wolfv/miniconda3/envs/ruby/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem jekyll (>= 0.a) with executable jekyll (Gem::GemNotFoundException)
```

Any ideas for the latter?

**Comment by wolfv** [comment]
OK when I set `export GEM_HOME=$CONDA_PREFIX/share/rubygems/` it works! :tada: 

Maybe we _should_ have an activate script for that? or can we add that to gemrc as well...

**Comment by scopatz** [comment]
Yeah we should have an activate script for that

**Comment by martibosch** [comment]
I am having an issue running bundler:

I have installed ruby (v3.1.2) using mamba, then installed bundler using gem (note that `which gem` gives me `/home/martibosch/mambaforge/bin/gem` in my base mamba env). Then, running `bundle exec jekyll serve` (or any bundle command basically) gives me

```
/home/martibosch/mambaforge/share/rubygems/bin/bundle: 6: exec: /home/martibosch/mambaforge/share/rubygems/bin/ruby: not found
```

so it is basically looking for ruby at `mambaforge/share/rubygems/bin` whereas ruby is at `/home/martibosch/mambaforge/bin/ruby`.

I have not changed anything so this is basically vanilla ruby installation from conda-forge, i.e., with `etc/conda/activate.d/ruby_activate.sh` being:

```
export GEM_HOME=$CONDA_PREFIX/share/rubygems/
export PATH="$CONDA_PREFIX/share/rubygems/bin:$PATH"
```

giving me a $PATH of

```
/home/martibosch/mambaforge/share/rubygems/bin:/home/martibosch/mambaforge/bin:/home/martibosch/mambaforge/share/rubygems/bin:/home/martibosch/mambaforge/condabin:/home/martibosch/.local/bin:...<bunch-of-no-mamba-stuff>
````

How can I thus use bundler with conda-forge ruby?

Thank you. Best,
Martí
